### ISSUE TITLE
Not working in jetpack compose

### ISSUE THREAD

**Issue by hmshohrab** [rafi0101/Android-Room-Database-Backup#28]
**Describe the bug**
Custiom dialog is not working

**Comment by rafi0101** [comment]
do you have any more information for me? That's why I actually created a bug report template where you get asked for some details!

**Comment by Marc-WAP** [comment]
I've ran into the same problem as @hmshohrab and found a fix. I'll create a PR within a minute.

The problem we're facing is that this module is not compatible with an Android app using Jetpack Compose instead of Fragments. 

This is due to the extension of `FragmentActivity`, which results in the following error:

`Cannot access 'androidx.fragment.app.FragmentActivity' which is a supertype of 'de.raphaelebner.roomdatabasebackup.core.RoomBackup'. Check your module classpath for missing or conflicting dependencies`

Removing this extension resolves this problem, and it seems like it also doesn't break the sample projects.
